/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * An ingredient required to make a drink.
 */
export class DrinkIngredient extends SpeakeasyBase {
    /**
     * The product code of an ingredient, only available when authenticated.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ingredientProductCode" })
    ingredientProductCode: string;

    /**
     * The number of units of the ingredient required to make the drink.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;
}
