/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of drink.
 */
export enum DrinkType {
    Cocktail = "cocktail",
    NonAlcoholic = "non-alcoholic",
    Beer = "beer",
    Wine = "wine",
    Spirit = "spirit",
    Other = "other",
}

/** @internal */
export namespace DrinkType$ {
    export const inboundSchema: z.ZodNativeEnum<typeof DrinkType> = z.nativeEnum(DrinkType);
    export const outboundSchema: z.ZodNativeEnum<typeof DrinkType> = inboundSchema;
}
