/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of order.
 */
export enum OrderType {
    Drink = "drink",
    Ingredient = "ingredient",
}

/** @internal */
export namespace OrderType$ {
    export const inboundSchema = z.nativeEnum(OrderType);
    export const outboundSchema = inboundSchema;
}
