/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { OrderType, OrderType$ } from "./ordertype.js";
import * as z from "zod";

/**
 * An order for a drink or ingredient.
 */
export type OrderInput = {
    /**
     * The product code of the drink or ingredient.
     */
    productCode: string;
    /**
     * The number of units of the drink or ingredient to order.
     */
    quantity: number;
    /**
     * The type of order.
     */
    type: OrderType;
};

/** @internal */
export namespace OrderInput$ {
    export const inboundSchema: z.ZodType<OrderInput, z.ZodTypeDef, unknown> = z.object({
        productCode: z.string(),
        quantity: z.number().int(),
        type: OrderType$.inboundSchema,
    });

    export type Outbound = {
        productCode: string;
        quantity: number;
        type: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, OrderInput> = z.object({
        productCode: z.string(),
        quantity: z.number().int(),
        type: OrderType$.outboundSchema,
    });
}
