/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of order.
 */
export enum OrderType {
    Drink = "drink",
    Ingredient = "ingredient",
}

/** @internal */
export namespace OrderType$ {
    export const inboundSchema: z.ZodNativeEnum<typeof OrderType> = z.nativeEnum(OrderType);
    export const outboundSchema: z.ZodNativeEnum<typeof OrderType> = inboundSchema;
}
