/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { DrinkType, DrinkType$ } from "./drinktype";
import * as z from "zod";

/**
 * The level of data included in the response.
 */
export enum PublicDrinkDataLevel {
    Unauthenticated = "unauthenticated",
}

export type PublicDrink = {
    /**
     * The level of data included in the response.
     */
    dataLevel?: PublicDrinkDataLevel | undefined;
    /**
     * The name of the drink.
     */
    name: string;
    /**
     * A photo of the drink.
     */
    photo?: string | undefined;
    /**
     * The price of one unit of the drink in US cents.
     */
    price: number;
    /**
     * The type of drink.
     */
    type?: DrinkType | undefined;
};

/** @internal */
export namespace PublicDrinkDataLevel$ {
    export const inboundSchema = z.nativeEnum(PublicDrinkDataLevel);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace PublicDrink$ {
    export const inboundSchema: z.ZodType<PublicDrink, z.ZodTypeDef, unknown> = z
        .object({
            dataLevel: PublicDrinkDataLevel$.inboundSchema.optional(),
            name: z.string(),
            photo: z.string().optional(),
            price: z.number(),
            type: DrinkType$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.dataLevel === undefined ? null : { dataLevel: v.dataLevel }),
                name: v.name,
                ...(v.photo === undefined ? null : { photo: v.photo }),
                price: v.price,
                ...(v.type === undefined ? null : { type: v.type }),
            };
        });

    export type Outbound = {
        dataLevel?: string | undefined;
        name: string;
        photo?: string | undefined;
        price: number;
        type?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PublicDrink> = z
        .object({
            dataLevel: PublicDrinkDataLevel$.outboundSchema.optional(),
            name: z.string(),
            photo: z.string().optional(),
            price: z.number(),
            type: DrinkType$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.dataLevel === undefined ? null : { dataLevel: v.dataLevel }),
                name: v.name,
                ...(v.photo === undefined ? null : { photo: v.photo }),
                price: v.price,
                ...(v.type === undefined ? null : { type: v.type }),
            };
        });
}
