/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";
import * as z from "zod";

export type StockUpdateResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * An unknown error occurred interacting with the API.
     */
    error?: shared.ErrorT | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

export type StockUpdateRequestBody = {
    drink?: shared.DrinkInput | undefined;
    ingredient?: shared.Ingredient | undefined;
};

/** @internal */
export namespace StockUpdateResponse$ {
    export const inboundSchema: z.ZodType<StockUpdateResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            Error: shared.ErrorT$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                Error: "error",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        Error?: shared.ErrorT$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, StockUpdateResponse> = z
        .object({
            contentType: z.string(),
            error: shared.ErrorT$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                error: "Error",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
            });
        });
}

/** @internal */
export namespace StockUpdateRequestBody$ {
    export const inboundSchema: z.ZodType<StockUpdateRequestBody, z.ZodTypeDef, unknown> = z.object(
        {
            drink: shared.DrinkInput$.inboundSchema.optional(),
            ingredient: shared.Ingredient$.inboundSchema.optional(),
        }
    );

    export type Outbound = {
        drink?: shared.DrinkInput$.Outbound | undefined;
        ingredient?: shared.Ingredient$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, StockUpdateRequestBody> =
        z.object({
            drink: shared.DrinkInput$.outboundSchema.optional(),
            ingredient: shared.Ingredient$.outboundSchema.optional(),
        });
}
