/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type StockUpdateResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * An unknown error occurred interacting with the API.
     */
    error?: shared.ErrorT | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

export type StockUpdateRequestBody = {
    drink?: shared.DrinkInput | undefined;
    ingredient?: shared.IngredientInput | undefined;
};

/** @internal */
export namespace StockUpdateResponse$ {
    export const inboundSchema: z.ZodType<StockUpdateResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            Error: shared.ErrorT$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.Error === undefined ? null : { error: v.Error }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        Error?: shared.ErrorT$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, StockUpdateResponse> = z
        .object({
            contentType: z.string(),
            error: shared.ErrorT$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.error === undefined ? null : { Error: v.error }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}

/** @internal */
export namespace StockUpdateRequestBody$ {
    export const inboundSchema: z.ZodType<StockUpdateRequestBody, z.ZodTypeDef, unknown> = z
        .object({
            drink: shared.DrinkInput$.inboundSchema.optional(),
            ingredient: shared.IngredientInput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.drink === undefined ? null : { drink: v.drink }),
                ...(v.ingredient === undefined ? null : { ingredient: v.ingredient }),
            };
        });

    export type Outbound = {
        drink?: shared.DrinkInput$.Outbound | undefined;
        ingredient?: shared.IngredientInput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, StockUpdateRequestBody> = z
        .object({
            drink: shared.DrinkInput$.outboundSchema.optional(),
            ingredient: shared.IngredientInput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.drink === undefined ? null : { drink: v.drink }),
                ...(v.ingredient === undefined ? null : { ingredient: v.ingredient }),
            };
        });
}
