/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives";
import * as shared from "../shared";
import * as z from "zod";

export type GetDrinkRequest = {
    name: string;
};

export type GetDrinkResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * A drink.
     */
    drink?: shared.Drink | undefined;
    /**
     * An unknown error occurred interacting with the API.
     */
    error?: shared.ErrorT | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetDrinkRequest$ {
    export const inboundSchema: z.ZodType<GetDrinkRequest, z.ZodTypeDef, unknown> = z.object({
        name: z.string(),
    });

    export type Outbound = {
        name: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDrinkRequest> = z.object({
        name: z.string(),
    });
}

/** @internal */
export namespace GetDrinkResponse$ {
    export const inboundSchema: z.ZodType<GetDrinkResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            Drink: shared.Drink$.inboundSchema.optional(),
            Error: shared.ErrorT$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                Drink: "drink",
                Error: "error",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        Drink?: shared.Drink$.Outbound | undefined;
        Error?: shared.ErrorT$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDrinkResponse> = z
        .object({
            contentType: z.string(),
            drink: shared.Drink$.outboundSchema.optional(),
            error: shared.ErrorT$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                drink: "Drink",
                error: "Error",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
            });
        });
}
