/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type GetDrinkRequest = {
    productCode: string;
};

export type GetDrinkResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * A drink.
     */
    drink?: shared.Drink | undefined;
    /**
     * An unknown error occurred interacting with the API.
     */
    error?: shared.ErrorT | undefined;
    headers: { [k: string]: Array<string> };
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetDrinkRequest$ {
    export const inboundSchema: z.ZodType<GetDrinkRequest, z.ZodTypeDef, unknown> = z
        .object({
            productCode: z.string(),
        })
        .transform((v) => {
            return {
                productCode: v.productCode,
            };
        });

    export type Outbound = {
        productCode: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDrinkRequest> = z
        .object({
            productCode: z.string(),
        })
        .transform((v) => {
            return {
                productCode: v.productCode,
            };
        });
}

/** @internal */
export namespace GetDrinkResponse$ {
    export const inboundSchema: z.ZodType<GetDrinkResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            Drink: shared.Drink$.inboundSchema.optional(),
            Error: shared.ErrorT$.inboundSchema.optional(),
            Headers: z.record(z.array(z.string())),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.Drink === undefined ? null : { drink: v.Drink }),
                ...(v.Error === undefined ? null : { error: v.Error }),
                headers: v.Headers,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        Drink?: shared.Drink$.Outbound | undefined;
        Error?: shared.ErrorT$.Outbound | undefined;
        Headers: { [k: string]: Array<string> };
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDrinkResponse> = z
        .object({
            contentType: z.string(),
            drink: shared.Drink$.outboundSchema.optional(),
            error: shared.ErrorT$.outboundSchema.optional(),
            headers: z.record(z.array(z.string())),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.drink === undefined ? null : { Drink: v.drink }),
                ...(v.error === undefined ? null : { Error: v.error }),
                Headers: v.headers,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
