/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";
import * as z from "zod";

export type ListDrinksRequest = {
    /**
     * The type of drink to filter by. If not provided all drinks will be returned.
     */
    drinkType?: shared.DrinkType | undefined;
};

export type ListDrinksResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * An unknown error occurred interacting with the API.
     */
    error?: shared.ErrorT | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * A list of drinks.
     */
    classes?: Array<shared.Drink> | undefined;
};

/** @internal */
export namespace ListDrinksRequest$ {
    export const inboundSchema: z.ZodType<ListDrinksRequest, z.ZodTypeDef, unknown> = z.object({
        drinkType: shared.DrinkType$.inboundSchema.optional(),
    });

    export type Outbound = {
        drinkType?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListDrinksRequest> = z.object({
        drinkType: shared.DrinkType$.outboundSchema.optional(),
    });
}

/** @internal */
export namespace ListDrinksResponse$ {
    export const inboundSchema: z.ZodType<ListDrinksResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            Error: shared.ErrorT$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            classes: z.array(shared.Drink$.inboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                Error: "error",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        Error?: shared.ErrorT$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
        classes?: Array<shared.Drink$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListDrinksResponse> = z
        .object({
            contentType: z.string(),
            error: shared.ErrorT$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            classes: z.array(shared.Drink$.outboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                error: "Error",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
            });
        });
}
