/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class UpdateDrinkRawRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "request, media_type=text/csv" })
    requestBody: Uint8Array;

    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=productCode" })
    productCode: string;
}

export class UpdateDrinkRawResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    body?: Uint8Array;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * The drink was updated successfully.
     */
    @SpeakeasyMetadata()
    drink?: shared.Drink;

    /**
     * An unknown error occurred interacting with the API.
     */
    @SpeakeasyMetadata()
    error?: shared.ErrorT;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;
}
