/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configSubscribeToWebhooks } from "../funcs/configSubscribeToWebhooks.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Config extends ClientSDK {
  /**
   * Subscribe to webhooks.
   *
   * @remarks
   * Subscribe to webhooks.
   */
  async subscribeToWebhooks(
    request: Array<operations.RequestBody>,
    options?: RequestOptions,
  ): Promise<operations.SubscribeToWebhooksResponse> {
    return unwrapAsync(configSubscribeToWebhooks(
      this,
      request,
      options,
    ));
  }
}
