/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { foodGetFood } from "../funcs/foodGetFood.js";
import { foodListFoods } from "../funcs/foodListFoods.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Food extends ClientSDK {
  /**
   * Get a food item.
   *
   * @remarks
   * Get a food item by name.
   */
  async getFood(
    name: string,
    options?: RequestOptions,
  ): Promise<operations.GetFoodResponse> {
    return unwrapAsync(foodGetFood(
      this,
      name,
      options,
    ));
  }

  /**
   * Get a list of food items.
   *
   * @remarks
   * Get a list of food items.
   */
  async listFoods(
    options?: RequestOptions,
  ): Promise<operations.ListFoodsResponse> {
    return unwrapAsync(foodListFoods(
      this,
      options,
    ));
  }
}
