/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @speakeasy-sdks/speakeasy-bar SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx drinksListDrinks.example.ts
 */

import { BarSDK } from "@speakeasy-sdks/speakeasy-bar";

const barSDK = new BarSDK({
  security: {
    apiKey: "<YOUR_API_KEY_HERE>",
  },
});

async function main() {
  const result = await barSDK.listDrinks();

  console.log(result);
}

main().catch(console.error);
