/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type CreateOrderOrderUpdateResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * An unknown error occurred interacting with the API.
     */
    error?: shared.ErrorT | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

export type CreateOrderOrderUpdateRequestBody = {
    /**
     * An order for a drink or ingredient.
     */
    order?: shared.OrderInput | undefined;
};

/** @internal */
export namespace CreateOrderOrderUpdateResponse$ {
    export const inboundSchema: z.ZodType<CreateOrderOrderUpdateResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            Error: shared.ErrorT$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.Error === undefined ? null : { error: v.Error }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        Error?: shared.ErrorT$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateOrderOrderUpdateResponse> =
        z
            .object({
                contentType: z.string(),
                error: shared.ErrorT$.outboundSchema.optional(),
                statusCode: z.number().int(),
                rawResponse: z.instanceof(Response).transform(() => {
                    throw new Error("Response cannot be serialized");
                }),
            })
            .transform((v) => {
                return {
                    ContentType: v.contentType,
                    ...(v.error === undefined ? null : { Error: v.error }),
                    StatusCode: v.statusCode,
                    RawResponse: v.rawResponse,
                };
            });
}

/** @internal */
export namespace CreateOrderOrderUpdateRequestBody$ {
    export const inboundSchema: z.ZodType<
        CreateOrderOrderUpdateRequestBody,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            order: shared.OrderInput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.order === undefined ? null : { order: v.order }),
            };
        });

    export type Outbound = {
        order?: shared.OrderInput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateOrderOrderUpdateRequestBody
    > = z
        .object({
            order: shared.OrderInput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.order === undefined ? null : { order: v.order }),
            };
        });
}
